"""Generalized algebraic theories and indexed Model fields."""

from didactic.gadt._ast import (
    App,
    Branch,
    Case,
    Hole,
    Let,
    SortExpr,
    Term,
    Var,
    app,
    branch,
    case,
    hole,
    let,
    term_from_spec,
    var,
)
from didactic.gadt._declarations import (
    GADT,
    Equation,
    Family,
    GADTDeclarationError,
    GADTReductionError,
    Motive,
    Operation,
    Parameter,
    param,
)
from didactic.gadt._indexed import IndexedBy, Universe, indexed_by

__all__ = [
    "GADT",
    "App",
    "Branch",
    "Case",
    "Equation",
    "Family",
    "GADTDeclarationError",
    "GADTReductionError",
    "Hole",
    "IndexedBy",
    "Let",
    "Motive",
    "Operation",
    "Parameter",
    "SortExpr",
    "Term",
    "Universe",
    "Var",
    "app",
    "branch",
    "case",
    "hole",
    "indexed_by",
    "let",
    "param",
    "term_from_spec",
    "var",
]
